modLoader="javafml"
loaderVersion="[40]"
license="GPL-3.0-or-later"
issueTrackerURL="https://git.alternerd.tv/the_vault-tweaks/issues"


[[mods]]
modId="the_vault_tweaks"
version="${file.jarVersion}"
displayName="The Vault Tweaks"
displayURL="https://git.alternerd.tv/the_vault-tweaks"
#logoFile="examplemod.png"
credits="A collection of tweaks for the Vault mod of the Vault Hunters mod pack."
authors="alterNERDtive"
description='''
A collection of tweaks for the Vault mod of the Vault Hunters mod pack.

There are some bug fixes and a lot of QoL and balance changes. See https://git.alternerd.tv/VaultHunters-tweaks
'''

[[dependencies.the_vault_tweaks]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.the_vault_tweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.the_vault_tweaks]]
    modId="the_vault"
    mandatory=true
    versionRange="[1.18.2-3.11.0.2551]"
    ordering="AFTER"
    side="BOTH"
